version: "3"
services:
  mariadb:
    build: ./requirements/mariadb
    stdin_open: true
    volumes:
      - /home/kkaneko/data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
